# Generated by Django 5.2.5 on 2025-08-30 01:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('giro', models.CharField(blank=True, help_text='Ej. Abarrotes, Ropa, Ferretería, etc.', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Arqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('ventas_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ventas_tarjeta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('retiros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_contado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Completado', max_length=10)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('ticket_numero', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], default='Efectivo', max_length=10)),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cambio_entregado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('arqueo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='inventario.arqueo')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cancelados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo de adquisición del producto por unidad/kg.', max_digits=10)),
                ('stock', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('precio_mayoreo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mayoreo_desde_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo (kg)'), ('unidad', 'Unidad (u)'), ('servicio', 'Servicio')], default='kg', max_length=10)),
                ('requiere_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=255)),
                ('arqueo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiros_del_arqueo', to='inventario.arqueo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
