# Generated by Django 5.2.5 on 2025-08-25 15:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('ventas_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ventas_tarjeta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('retiros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_contado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
            ],
        ),
    ]
