# Generated by Django 5.2.5 on 2025-08-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_arqueo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cambio_entregado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
