# Generated by Django 5.2.5 on 2025-08-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_pedido_cambio_entregado_pedido_monto_recibido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='requiere_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramo (kg)'), ('unidad', 'Unidad (u)')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
