# Generated by Django 5.2.5 on 2025-08-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_producto_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo de adquisición del producto por unidad/kg.', max_digits=10),
        ),
    ]
