# Generated by Django 5.2.5 on 2025-08-27 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='arqueo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='inventario.arqueo'),
        ),
        migrations.AddField(
            model_name='retiro',
            name='arqueo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiros_del_arqueo', to='inventario.arqueo'),
        ),
    ]
