# Generated by Django 5.2.5 on 2025-08-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_pedido_arqueo_retiro_arqueo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='giro',
            field=models.CharField(blank=True, help_text='Ej. Abarrotes, Ropa, Ferretería, etc.', max_length=100, null=True),
        ),
    ]
