# Generated by Django 5.2.5 on 2025-08-28 15:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_empresa_giro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='monto_reembolso',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
