# Generated by Django 5.2.5 on 2025-08-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_pedido_monto_reembolso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='monto_reembolso',
        ),
    ]
