# Generated by Django 5.2.5 on 2025-08-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_remove_pedido_monto_reembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ticket_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
