# Generated by Django 5.2.5 on 2025-08-28 21:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_arqueo_monto_inicial_siguiente_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueo',
            name='monto_inicial_caja',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
