# Generated by Django 5.2.5 on 2025-08-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_arqueo_monto_inicial_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arqueo',
            name='monto_inicial_caja',
        ),
        migrations.RemoveField(
            model_name='arqueo',
            name='monto_inicial_siguiente_turno',
        ),
    ]
