# Generated by Django 5.2.5 on 2025-08-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_remove_arqueo_monto_inicial_caja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramo (kg)'), ('unidad', 'Unidad (u)'), ('servicio', 'Servicio')], default='kg', max_length=10),
        ),
    ]
