# Generated by Django 5.2.5 on 2025-08-29 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_alter_producto_unidad_medida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Completado', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
