# Usa una imagen oficial de Python como base
FROM python:3.11-slim

# Establece las variables de entorno para la configuración de Django
ENV DJANGO_SETTINGS_MODULE=config.settings
ENV PYTHONUNBUFFERED=1

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de requerimientos e instálalos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código de tu aplicación
COPY . .

# Expone el puerto 8000 que Gunicorn usará
EXPOSE 8000

# Comando para correr la aplicación con Gunicorn
CMD gunicorn config.wsgi:application --bind 0.0.0.0:8000